/* eslint-disable jsx-a11y/anchor-is-valid */
/* eslint-disable jsx-a11y/alt-text */
import "../CSS/image.css";
import "../CSS/Footer.css";

import wurLogo from "../img/WUR_logo.png";
import React, { Component } from "react";
import M from "materialize-css";

export default class Footer extends Component {
  componentDidMount() {
    M.AutoInit();
  }
  render() {
    return (
      <div className="main-footer">
        <div className="container">
          <a href ="https://www.wur.nl/nl/Onderzoek-Resultaten/Onderzoeksinstituten/food-safety-research.htm" ><img className="wurlogo" src={wurLogo} /></a>
          <h5>
            <a class="modal-trigger" data-target="disclaimer">
              Disclaimer
            </a>{" "}
            |{" "}
            <a class="modal-trigger" data-target="copyright">
              Copyright
            </a>{" "}
            |{" "}
            <a class="modal-trigger" data-target="thanks">
              Thanks
            </a>
          </h5>
          <hr />
          <div className="row">
              &copy;{new Date().getFullYear} Allermatch | All rights reserved
          </div>
        </div>
        {/* Modals used for displaying information about references are below. */}
        <div id="disclaimer" class="modal">
          <div class="modal-content">
            <h4>Disclaimer</h4>
            <p>
              This public, non-commercial webtool has been constructed solely
              for the purpose of investigational use by scientific researchers,
              regulatory professionals, and other interested parties. This
              webtool is not meant to be used, among others, for commercial
              purposes or the automatic generation of commands for this
              website's facilities by other computers. While the Allermatch
              <sup>tm</sup> website aims at providing data that are as accurate
              as possible to the current state of knowledge, website users are
              strongly recommended to check the data and outcomes that they
              retrieve from this website against original scientific literature
              and other sources of information. <br /> No rights or damage can
              be claimed based on data provided and/or generated by this website
              and its facilities, including, but not limited to, information,
              search facilities, and outcomes of search actions carried out with
              the aid of the data and search facilities made available to
              website users. The sequences of proteins stored in the website's
              database have been obtained from third party databases and are
              therefore liable to these third party database provider's
              copyrights (See our copyright statement). <br />
              Users should respect the third party database providers rights to
              the sequence information. Data obtained through this webtool may
              be published without the explicit written consent of the webtool
              owners, provided that the data characteristics are not modified
              and the webtool is acknowledged as the source of these data, while
              the acknowledgement should include the webtool's name Allermatch
              <sup>tm</sup>, its URL{" "}
              <a href="http://allermatch.org/">http://allermatch.org/</a>, and
              the date of its last update during use. Notwithstanding the
              previous statements, neither the authors' nor third party database
              provider's rights should be affected.
            </p>
          </div>
          <div class="modal-footer">
            <a href="#!" class="modal-close waves-effect waves-green btn-flat">
              Close
            </a>
          </div>
        </div>
        <div id="copyright" class="modal">
          <div class="modal-content">
            <h4>Copyright</h4>
            <p>
              The protein sequences in the Allermatch<sup>tm</sup> database have
              been obtained, eventually after processing (e.g. removal of pro-
              and signal- peptides), from publicly available databases. It is
              therefore important that users of the Allermatch<sup>tm</sup>{" "}
              website respect the copyrights pertaining to the sequences. The
              following statements have been copied from the websites of the
              source databases:
            </p>
            <h5>UniProt</h5>
            <p>
              UniProt has chosen to apply the Creative Commons
              Attribution-NoDerivs License to all copyrightable parts of our
              databases. This means that you are free to copy, distribute,
              display and make commercial use of these databases in all
              legislations, provided you give UniProt credit*. However, if you
              intend to distribute a modified version of one of our databases,
              you must ask UniProt for permission first. UniProt makes no
              warranties regarding the correctness of the data, and disclaim
              liability for damages resulting from its use. It cannot provide
              unrestricted permission regarding the use of the data, as some
              data may be covered by patents or other rights.
            </p>
            <p>
              * How to cite UniProt: The UniProt Consortium Reorganizing the
              protein space at the Universal Protein Resource (UniProt) Nucleic
              Acids Res. 40: D71-D75 (2012).
            </p>
            <p>
              See also the{" "}
              <a href="http://www.uniprot.org/help/license">UniProt</a> website
            </p>
            <h5>GenBank/GenPept (NLM, NCBI) Copyright</h5>
            <p>
              Information that is created by or for the US government on this
              site is within the public domain. Public domain information on the
              National Library of Medicine (NLM) Web pages may be freely
              distributed and copied. However, it is requested that in any
              subsequent use of this work, NLM be given appropriate
              acknowledgment.
            </p>
            <p>
              This site contains resources such as, but not limited to, PubMed
              Central (see{" "}
              <a href="http://www.ncbi.nlm.nih.gov/pmc/about/copyright/">
                PMC Copyright Notice
              </a>
              ), Bookshelf (see{" "}
              <a href="http://www.ncbi.nlm.nih.gov/books/about/copyright/">
                Bookshelf Copyright Notice
              </a>
              ), OMIM, and PubChem which incorporate material contributed or
              licensed by individuals, companies, or organizations that may be
              protected by U.S. and foreign copyright laws. All persons
              reproducing, redistributing, or making commercial use of this
              information are expected to adhere to the terms and conditions
              asserted by the copyright holder. Transmission or reproduction of
              protected items beyond that allowed by{" "}
              <a href="http://www.copyright.gov/fls/fl102.html">
                fair use (PDF)
              </a>{" "}
              as defined in the copyright laws requires the written permission
              of the copyright owners.
            </p>
            <p>
              <b>Molecular Database Availability</b>
              <br />
              Databases of molecular data on the NCBI Web site include such
              examples as nucleotide sequences (GenBank), protein sequences,
              macromolecular structures, molecular variation, gene expression,
              and mapping data. They are designed to provide and encourage
              access within the scientific community to sources of current and
              comprehensive information. Therefore, NCBI itself places no
              restrictions on the use or distribution of the data contained
              therein. However, some submitters of the original data may claim
              patent, copyright, or other intellectual property rights in all or
              a portion of the data they have submitted. NCBI is not in a
              position to assess the validity of such claims and, therefore,
              cannot provide comment or unrestricted permission concerning the
              use, copying, or distribution of the information contained in the
              molecular databases.{" "}
            </p>
            See also the{" "}
            <a href="https://www.ncbi.nlm.nih.gov/home/about/policies/">
              NCBI
            </a>{" "}
            website
          </div>
          <div class="modal-footer">
            <a href="#!" class="modal-close waves-effect waves-green btn-flat">
              Close
            </a>
          </div>
        </div>
        <div id="thanks" class="modal">
          <div class="modal-content">
            <h4>Acknowledgement</h4>
            <p>
              Financial support for this webtool from Plant Research
              International, WFSR - Wageningen University and Research, and the
              Dutch Ministry of Agriculture, Nature, and Food Quality (Research
              Programs 378, 390, and 404 [North-South]) is gratefully
              acknowledged. Maintenance is however not funded and is currently
              performed because of author's motivation.
            </p>
            <p>
              In 2020 Jordan Dekker from HAN university, updated the tool and
              added high throughput possibilities as part of his internship
              during his study for bio-informatician.
            </p>
            <p>
              In 2021 the website was redesigned and rebuilt by Glenn Hulscher from VisioLab
              <sup>tm</sup> as a project as part of Glenn his internship at WFSR
              - Wageningen University and Research during his study for
              bio-informatician at HAN university.
            </p>
          </div>
          <div class="modal-footer">
            <a href="#!" class="modal-close waves-effect waves-green btn-flat">
              Close
            </a>
          </div>
        </div>
        {/* End of Modals */}
      </div>
    );
  }
}
